// Package capability defines the decoupled Capability contract of the Izen
// Agent Runtime V3: a single source of truth for what a capability can do,
// how it presents itself to models, and how it validates artifacts.
//
// A Capability owns everything about itself — its prompt representation is
// generated by the capability (model-tier aware), and its validation logic
// lives on the capability. The Registry only stores and resolves them; it
// never interprets their semantics.
package capability

import "context"

// CapabilityID uniquely identifies a capability within a Registry.
type CapabilityID string

// String returns the machine-readable id label.
func (c CapabilityID) String() string { return string(c) }

// ValidationResult is the outcome of a capability validating an artifact.
// It is deliberately evidence-shaped: a boolean verdict plus the exact
// reasons behind it, never a floating confidence score.
type ValidationResult struct {
	// Passed reports whether validation succeeded.
	Passed bool
	// Reasons lists the human-readable justifications for the verdict.
	Reasons []string
}

// Pass returns a passing ValidationResult. Optional reasons document why.
func Pass(reasons ...string) ValidationResult {
	return ValidationResult{Passed: true, Reasons: append([]string(nil), reasons...)}
}

// Fail returns a failing ValidationResult carrying the rejection reasons.
func Fail(reasons ...string) ValidationResult {
	return ValidationResult{Passed: false, Reasons: append([]string(nil), reasons...)}
}

// Failed reports whether validation rejected the artifact.
func (v ValidationResult) Failed() bool { return !v.Passed }

// Capability is the single-source-of-truth contract for one workspace
// capability. Implementations are decoupled: each capability defines its own
// prompt representation and its own validation logic.
type Capability interface {
	// ID returns the unique identifier of the capability.
	ID() CapabilityID
	// Description summarizes what the capability provides.
	Description() string
	// PromptRepresentation renders the capability as instructions for a
	// model. modelTier selects between e.g. "small" and "full" verbosity.
	PromptRepresentation(modelTier string) string
	// Validate checks an artifact's data against this capability's rules and
	// returns a deterministic ValidationResult.
	Validate(ctx context.Context, data []byte) ValidationResult
	// RuntimeRequirements lists the tools/services the capability needs at
	// runtime (e.g. "go toolchain", "docker").
	RuntimeRequirements() []string
}
