package session

import (
	"encoding/json"
	"os"
	"path/filepath"
	"time"

	"github.com/PizenLabs/izen/internal/modes"
	"github.com/PizenLabs/izen/internal/modes/plan"
)

// ContextLedgerPath is the on-disk location of the handoff ledger, the single
// source of truth for state passed between modes. It lives under .izen so it is
// scoped to the project and cleared alongside the rest of the session state.
const ContextLedgerPath = ".izen/context_ledger.json"

// ContextLedger is the strongly-typed, serializable handoff state compiled by a
// source mode and consumed by a target mode. It replaces the leaky, ad-hoc
// "Transaction Cache" and "Context Sanitization" layers with a single canonical
// record written to disk on every mode transition.
//
// Absolute invalidation is guaranteed by treating this file as the only source
// of truth: on mode switch the previous ledger is overwritten (not merged), so
// no stale prompts, build logs, or chat history can leak across modes.
type ContextLedger struct {
	// ID uniquely identifies this handoff transaction (UUID or timestamp).
	ID string `json:"id"`
	// SourceMode is the mode that compiled this ledger (e.g., "investigate").
	SourceMode string `json:"source_mode"`
	// TargetFile is the file currently being audited/fixed, if any.
	TargetFile string `json:"target_file,omitempty"`
	// Diagnostics carries raw error outputs or test logs, if any.
	Diagnostics string `json:"diagnostics,omitempty"`
	// Tasks are generated by /plan and consumed by /build.
	Tasks []plan.AtomicTask `json:"tasks,omitempty"`
	// TaskStatus tracks the fail-fast lifecycle of each task in Tasks, keyed
	// by TaskID. Values: "pending", "completed", "failed". It is the
	// authoritative execution mirror for the /build machine.
	TaskStatus map[int]string `json:"task_status,omitempty"`
	// CreatedAt records when this ledger was compiled.
	CreatedAt time.Time `json:"created_at"`
	// path is the on-disk location; not serialized.
	path string
}

// NewContextLedger constructs a fresh ledger for the given source mode with a
// populated ID and timestamp. The returned ledger is empty of payload fields,
// ensuring no inherited state leaks across a mode switch.
func NewContextLedger(source modes.Mode) *ContextLedger {
	return &ContextLedger{
		ID:         newLedgerID(),
		SourceMode: source.String(),
		CreatedAt:  time.Now(),
	}
}

// LoadContextLedger reads the on-disk ledger. If the file does not exist it
// returns an empty (non-nil) ledger rather than an error, so callers can treat
// absence as a clean slate.
func LoadContextLedger() (*ContextLedger, error) {
	data, err := os.ReadFile(ContextLedgerPath)
	if err != nil {
		if os.IsNotExist(err) {
			return &ContextLedger{}, nil
		}
		return nil, err
	}

	var l ContextLedger
	if err := json.Unmarshal(data, &l); err != nil {
		return nil, err
	}
	l.path = ContextLedgerPath
	if l.Tasks == nil {
		l.Tasks = []plan.AtomicTask{}
	}
	return &l, nil
}

// Save writes the ledger to disk as the single source of truth. It is an
// absolute overwrite: any previously persisted ledger (and thus any stale
// handoff state) is replaced.
func (l *ContextLedger) Save() error {
	if l.path == "" {
		l.path = ContextLedgerPath
	}
	l.CreatedAt = time.Now()

	dir := filepath.Dir(l.path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	data, err := json.MarshalIndent(l, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(l.path, data, 0644)
}

// Invalidate erases all handoff state by overwriting the ledger with a fresh
// record for the incoming mode. This guarantees absolute memory invalidation on
// mode switch: no previous prompts, diagnostics, or tasks survive.
func (l *ContextLedger) Invalidate(incoming modes.Mode) error {
	*l = *NewContextLedger(incoming)
	return l.Save()
}

// Reload re-reads the ledger from disk, discarding any in-memory mutations.
func (l *ContextLedger) Reload() error {
	path := l.path
	if path == "" {
		path = ContextLedgerPath
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	var reloaded ContextLedger
	if err := json.Unmarshal(data, &reloaded); err != nil {
		return err
	}
	reloaded.path = path
	*l = reloaded
	return nil
}

// newLedgerID returns a timestamp-based unique identifier for a handoff
// transaction. It is monotonic with nanosecond precision, sufficient for
// distinguishing sequential mode transitions within a session.
func newLedgerID() string {
	return time.Now().UTC().Format("20060102T150405.000000000Z")
}
