package session

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/PizenLabs/izen/internal/modes"
	"github.com/PizenLabs/izen/internal/modes/plan"
)

// ContextLedgerPath is the on-disk location of the handoff ledger, the single
// source of truth for state passed between modes. It lives under .izen so it is
// scoped to the project and cleared alongside the rest of the session state.
const ContextLedgerPath = ".izen/context_ledger.json"

// ContextLedger is the strongly-typed, serializable handoff state compiled by a
// source mode and consumed by a target mode. It replaces the leaky, ad-hoc
// "Transaction Cache" and "Context Sanitization" layers with a single canonical
// record written to disk on every mode transition.
//
// Absolute invalidation is guaranteed by treating this file as the only source
// of truth: on mode switch the previous ledger is overwritten (not merged), so
// no stale prompts, build logs, or chat history can leak across modes.
//
// The ledger follows the Izen Daily Lifecycle Philosophy: operational data is
// separated, assigned sequential IDs, and injected as small analytical packets
// (LedgerPacket) so that downstream modes can process each item deterministically
// without the Developer losing state between modes.
type ContextLedger struct {
	// ID uniquely identifies this handoff transaction (UUID or timestamp).
	ID string `json:"id"`
	// SourceMode is the mode that compiled this ledger (e.g., "investigate").
	SourceMode string `json:"source_mode"`
	// TargetFile is the file currently being audited/fixed, if any.
	TargetFile string `json:"target_file,omitempty"`
	// Diagnostics carries raw error outputs or test logs, if any.
	Diagnostics string `json:"diagnostics,omitempty"`
	// Packets are the sequential, ID-tagged analytical packets injected by a
	// source mode (e.g. /investigate). Each packet is a self-contained unit of
	// forensic work — a finding, a targeted file, a hypothesis, or a stack
	// frame — that the next mode consumes by its sequential PacketID. This is
	// the canonical home of the structured diagnostic payload: it is NEVER
	// blind-sanitized away, only appended to, so state survives a mode switch.
	Packets []LedgerPacket `json:"packets,omitempty"`
	// Tasks are generated by /plan and consumed by /build.
	Tasks []plan.AtomicTask `json:"tasks,omitempty"`
	// TaskStatus tracks the fail-fast lifecycle of each task in Tasks, keyed
	// by TaskID. Values: "pending", "completed", "failed". It is the
	// authoritative execution mirror for the /build machine.
	TaskStatus map[int]string `json:"task_status,omitempty"`
	// CreatedAt records when this ledger was compiled.
	CreatedAt time.Time `json:"created_at"`
	// path is the on-disk location; not serialized.
	path string
}

// LedgerPacket is a single, ID-sequenced analytical unit inside the
// ContextLedger. /investigate dissects the failure point into these small
// packets so /plan can process each one deterministically and the Developer
// retains a precise, addressable view of the forensic work.
type LedgerPacket struct {
	// PacketID is the sequential, 1-based position of this packet in the
	// investigation. It is assigned monotonically by InjectPacket and used by
	// downstream modes to reference and lock specific items.
	PacketID int `json:"packet_id"`
	// Kind classifies the packet (e.g. "diagnostic", "target", "hypothesis",
	// "evidence", "stack_frame", "root_cause").
	Kind string `json:"kind"`
	// Title is a short human-readable label for the packet.
	Title string `json:"title,omitempty"`
	// Payload is the operational data for the packet. It is preserved verbatim
	// — never truncated — so the next mode receives the full structured signal.
	Payload string `json:"payload,omitempty"`
	// File and Line optionally anchor the packet to a precise code coordinate.
	File string `json:"file,omitempty"`
	Line int    `json:"line,omitempty"`
	// Confidence optionally carries a 0..1 relevance score for the packet.
	Confidence float64 `json:"confidence,omitempty"`
}

// NewContextLedger constructs a fresh ledger for the given source mode with a
// populated ID and timestamp. The returned ledger is empty of payload fields,
// ensuring no inherited state leaks across a mode switch.
func NewContextLedger(source modes.Mode) *ContextLedger {
	return &ContextLedger{
		ID:         newLedgerID(),
		SourceMode: source.String(),
		CreatedAt:  time.Now(),
	}
}

// InjectPacket appends a new sequentially-ID'd analytical packet to the ledger.
// It assigns the next monotonic PacketID (1-based) and is safe to call
// repeatedly during a single /investigate run. The incoming packet's PacketID
// is overwritten so callers need not compute sequencing themselves. The full
// payload is preserved verbatim — the ledger must never blind-sanitize packets.
func (l *ContextLedger) InjectPacket(p LedgerPacket) LedgerPacket {
	if l.Packets == nil {
		l.Packets = []LedgerPacket{}
	}
	p.PacketID = len(l.Packets) + 1
	l.Packets = append(l.Packets, p)
	return p
}

// PacketByID returns the packet with the given sequential ID, or nil if absent.
func (l *ContextLedger) PacketByID(id int) *LedgerPacket {
	for i := range l.Packets {
		if l.Packets[i].PacketID == id {
			return &l.Packets[i]
		}
	}
	return nil
}

// PacketCount returns the number of injected analytical packets.
func (l *ContextLedger) PacketCount() int {
	return len(l.Packets)
}

// PacketsByKind returns all packets whose Kind matches the given value, in
// sequential (PacketID) order.
func (l *ContextLedger) PacketsByKind(kind string) []LedgerPacket {
	var out []LedgerPacket
	for _, p := range l.Packets {
		if p.Kind == kind {
			out = append(out, p)
		}
	}
	return out
}

// LoadContextLedger reads the on-disk ledger. If the file does not exist it
// returns an empty (non-nil) ledger rather than an error, so callers can treat
// absence as a clean slate.
func LoadContextLedger() (*ContextLedger, error) {
	data, err := os.ReadFile(ContextLedgerPath)
	if err != nil {
		if os.IsNotExist(err) {
			return &ContextLedger{}, nil
		}
		return nil, err
	}

	var l ContextLedger
	if err := json.Unmarshal(data, &l); err != nil {
		return nil, err
	}
	l.path = ContextLedgerPath
	if l.Tasks == nil {
		l.Tasks = []plan.AtomicTask{}
	}
	return &l, nil
}

// Save writes the ledger to disk as the single source of truth. It is an
// absolute overwrite: any previously persisted ledger (and thus any stale
// handoff state) is replaced.
func (l *ContextLedger) Save() error {
	if l.path == "" {
		l.path = ContextLedgerPath
	}
	l.CreatedAt = time.Now()

	dir := filepath.Dir(l.path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	data, err := json.MarshalIndent(l, "", "  ")
	if err != nil {
		return err
	}

	// Open with O_SYNC so each write is flushed to disk synchronously,
	// preventing a race where a consumer (e.g. /plan) reads a partially
	// flushed ledger and falls back to stale/stale-state behaviour.
	f, err := os.OpenFile(l.path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC|os.O_SYNC, 0644)
	if err != nil {
		return err
	}
	if _, err := f.Write(data); err != nil {
		_ = f.Close()
		return err
	}
	// Belt-and-suspenders: force the OS buffer to disk before returning.
	if err := f.Sync(); err != nil {
		_ = f.Close()
		return err
	}
	return f.Close()
}

// Invalidate erases all handoff state by overwriting the ledger with a fresh
// record for the incoming mode. This guarantees absolute memory invalidation on
// mode switch: no previous prompts, diagnostics, or tasks survive.
func (l *ContextLedger) Invalidate(incoming modes.Mode) error {
	*l = *NewContextLedger(incoming)
	return l.Save()
}

// Reload re-reads the ledger from disk, discarding any in-memory mutations.
func (l *ContextLedger) Reload() error {
	path := l.path
	if path == "" {
		path = ContextLedgerPath
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	var reloaded ContextLedger
	if err := json.Unmarshal(data, &reloaded); err != nil {
		return err
	}
	reloaded.path = path
	*l = reloaded
	return nil
}

// newLedgerID returns a timestamp-based unique identifier for a handoff
// transaction. It is monotonic with nanosecond precision, sufficient for
// distinguishing sequential mode transitions within a session.
func newLedgerID() string {
	return time.Now().UTC().Format("20060102T150405.000000000Z")
}

// FormatPacketsForPlan renders the injected analytical packets as a structured,
// ID-indexed block for /plan consumption. Each packet is emitted with its
// sequential PacketID so the plan engine can reference and lock specific items
// deterministically. The payload is serialized verbatim — this is the
// operational data structure that must survive the mode transition.
func (l *ContextLedger) FormatPacketsForPlan() string {
	var b strings.Builder
	if len(l.Packets) == 0 {
		return ""
	}
	fmt.Fprintf(&b, "### ANALYTICAL PACKETS (sequential, ID-addressed)\n")
	fmt.Fprintf(&b, "Total packets: %d\n", len(l.Packets))
	for _, p := range l.Packets {
		fmt.Fprintf(&b, "\n[PKT-%d] kind=%s", p.PacketID, p.Kind)
		if p.Title != "" {
			fmt.Fprintf(&b, " title=%q", p.Title)
		}
		if p.File != "" {
			fmt.Fprintf(&b, " file=%s", p.File)
			if p.Line > 0 {
				fmt.Fprintf(&b, ":%d", p.Line)
			}
		}
		if p.Confidence > 0 {
			fmt.Fprintf(&b, " confidence=%.2f", p.Confidence)
		}
		fmt.Fprintf(&b, "\n")
		if p.Payload != "" {
			for _, line := range strings.Split(p.Payload, "\n") {
				fmt.Fprintf(&b, "  %s\n", line)
			}
		}
	}
	return strings.TrimRight(b.String(), "\n")
}
