name: Codecov

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: read
  actions: read

jobs:
  upload:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v8
        with:
          name: coverage-go
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: ls -R

      - uses: codecov/codecov-action@v5
        with:
          files: coverage.out
          fail_ci_if_error: true
